/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    APIList: typeof import('./src/components/APIList.vue')['default']
    Checkbox: typeof import('./src/components/checkbox.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JoinPage: typeof import('./src/components/JoinPage.vue')['default']
  }
}
